{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 1058325848,
                "osm_key": "building",
                "osm_value": "house",
                "type": "house",
                "postcode": "49333",
                "housenumber": "490",
                "countrycode": "US",
                "country": "United States",
                "city": "Middleville",
                "street": "Oak Meadow Drive",
                "state": "MI",
                "county": "Barry",
                "extent": [-85.4804703, 42.7163756, -85.4803401, 42.7162707],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.4804052, 42.716323149999994],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 17731258,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49333",
                "countrycode": "US",
                "name": "Tanglewood Drive",
                "country": "United States",
                "city": "Middleville",
                "state": "Michigan",
                "county": "Barry",
                "extent": [-85.4599715, 42.7197241, -85.4574609, 42.7194443],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.4586982792198, 42.71960583782718],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 17861365,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49546",
                "countrycode": "US",
                "name": "Tanglewood Drive Southeast",
                "country": "United States",
                "district": "Cascade Charter Township",
                "state": "Michigan",
                "county": "Kent",
                "extent": [-85.509517, 42.90336, -85.500914, 42.900787],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.50481303325992, 42.90118537556417],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 17714128,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49078",
                "countrycode": "US",
                "name": "Tanglewood Drive",
                "country": "United States",
                "city": "Otsego Township",
                "state": "Michigan",
                "county": "Allegan",
                "extent": [-85.711589, 42.449449, -85.711549, 42.448284],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.71156900945392, 42.4488664996753],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 17841626,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49024",
                "countrycode": "US",
                "name": "Tanglewood Drive",
                "country": "United States",
                "city": "Portage",
                "state": "Michigan",
                "county": "Kalamazoo",
                "extent": [-85.603514, 42.205107, -85.602397, 42.20505],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.60295026469225, 42.20505390556424],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 17813119,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49331",
                "countrycode": "US",
                "name": "Tanglewood Drive",
                "country": "United States",
                "city": "Boston Township",
                "state": "Michigan",
                "county": "Ionia",
                "extent": [-85.2664403, 42.9005544, -85.2635843, 42.8976719],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.26373816217207, 42.89784793323116],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 17948434,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49424",
                "countrycode": "US",
                "name": "Tanglewood Drive",
                "country": "United States",
                "city": "Park Township",
                "state": "Michigan",
                "county": "Ottawa",
                "extent": [-86.2027767, 42.793429, -86.201715, 42.7899184],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-86.20253517425728, 42.79192052100467],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 484596830,
                "osm_key": "building",
                "osm_value": "commercial",
                "type": "house",
                "postcode": "49333",
                "countrycode": "US",
                "name": "Middleville Towne Center Mall",
                "country": "United States",
                "city": "Middleville",
                "street": "Town Center Drive",
                "state": "MI",
                "county": "Barry",
                "extent": [-85.4730018, 42.7175284, -85.4713526, 42.7168484],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.47247608595737, 42.717156],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 17712166,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49895",
                "countrycode": "US",
                "name": "Tanglewood Drive",
                "country": "United States",
                "city": "Au Train",
                "state": "Michigan",
                "county": "Alger",
                "extent": [-86.7280493, 46.1729672, -86.725104, 46.169954],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-86.72581841500072, 46.17180556476882],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 17916162,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49756",
                "countrycode": "US",
                "name": "Tanglewood Drive",
                "country": "United States",
                "city": "Albert Township",
                "district": "Vienna Junction",
                "state": "Michigan",
                "county": "Montmorency",
                "extent": [-84.328149, 44.887634, -84.327955, 44.8839327],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-84.32796935748569, 44.88577520944417],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 261258533,
                "osm_key": "highway",
                "osm_value": "service",
                "type": "street",
                "postcode": "49707",
                "countrycode": "US",
                "name": "Tanglewood Drive",
                "country": "United States",
                "city": "Alpena Township",
                "state": "Michigan",
                "county": "Alpena",
                "extent": [-83.4767856, 45.0900074, -83.4758649, 45.0896248],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-83.4763609278025, 45.08991143488726],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "N",
                "osm_id": 6027269492,
                "osm_key": "place",
                "osm_value": "house",
                "type": "house",
                "postcode": "33033",
                "housenumber": "490",
                "countrycode": "US",
                "country": "United States",
                "city": "Homestead",
                "street": "Southeast 30th Drive",
                "state": "FL",
                "county": "Miami-Dade",
            },
            "geometry": {"type": "Point", "coordinates": [-80.4328583, 25.4654172]},
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 262967779,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49333",
                "countrycode": "US",
                "name": "Cider Mill Drive",
                "country": "United States",
                "city": "Middleville",
                "state": "Michigan",
                "county": "Barry",
                "extent": [-85.461695, 42.7214035, -85.4609672, 42.7213647],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.46132830479624, 42.72136502033986],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 262943402,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49333",
                "countrycode": "US",
                "name": "Misty Ridge Drive",
                "country": "United States",
                "city": "Middleville",
                "state": "Michigan",
                "county": "Barry",
                "extent": [-85.477011, 42.7057344, -85.4721974, 42.7042011],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.47436135915822, 42.70430134667916],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 17726346,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49333",
                "countrycode": "US",
                "name": "Eagle Drive",
                "country": "United States",
                "city": "Middleville",
                "state": "Michigan",
                "county": "Barry",
            },
            "geometry": {"type": "Point", "coordinates": [-85.46002985, 42.7227784]},
        },
    ],
    "query": "490 Tanglewood Drive Southeast, Middleville MI",
}
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 1343865607,
                "osm_key": "amenity",
                "osm_value": "school",
                "type": "house",
                "postcode": "49506",
                "countrycode": "US",
                "name": "Grand Rapids Christian High School",
                "country": "United States",
                "city": "Grand Rapids",
                "district": "Third Ward",
                "street": "Tecumseh Drive Southeast",
                "state": "Michigan",
                "county": "Kent",
                "extent": [-85.6235473, 42.9230384, -85.6185262, 42.9164642],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.62268785994316, 42.9196993],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 255822806,
                "osm_key": "amenity",
                "osm_value": "school",
                "type": "house",
                "postcode": "49506",
                "housenumber": "2211",
                "countrycode": "US",
                "name": "East Grand Rapids High School",
                "country": "United States",
                "city": "Grand Rapids",
                "street": "Lake Drive Southeast",
                "state": "MI",
                "county": "Kent",
                "extent": [-85.6153632, 42.9501398, -85.6102463, 42.9465213],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.61291642701656, 42.948215250000004],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 1099432025,
                "osm_key": "building",
                "osm_value": "house",
                "type": "house",
                "postcode": "49503",
                "housenumber": "258",
                "countrycode": "US",
                "country": "United States",
                "city": "Grand Rapids",
                "district": "Third Ward",
                "street": "Madison Avenue Southeast",
                "state": "MI",
                "county": "Kent",
                "extent": [-85.658969, 42.957767, -85.658678, 42.957662],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.65882342445997, 42.957699],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 1112600343,
                "osm_key": "building",
                "osm_value": "house",
                "type": "house",
                "postcode": "49503",
                "housenumber": "258",
                "countrycode": "US",
                "country": "United States",
                "city": "Grand Rapids",
                "district": "Third Ward",
                "street": "James Avenue Southeast",
                "state": "MI",
                "county": "Kent",
                "extent": [-85.6528701, 42.9578082, -85.6526543, 42.9577236],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.65276222302296, 42.9577659],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 357834264,
                "osm_key": "highway",
                "osm_value": "service",
                "type": "street",
                "postcode": "49506",
                "countrycode": "US",
                "name": "Grand Rapids Dominican Northeast Drive",
                "country": "United States",
                "city": "Grand Rapids",
                "state": "Michigan",
                "county": "Kent",
                "extent": [-85.6184724, 42.9655086, -85.6179305, 42.9645856],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.61819426425282, 42.965046886225146],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 17782779,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "48827",
                "countrycode": "US",
                "name": "Grandview Drive",
                "country": "United States",
                "city": "Eaton Rapids",
                "state": "Michigan",
                "county": "Eaton",
                "extent": [-84.651507, 42.526321, -84.648871, 42.525723],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-84.65017896972616, 42.52617591002296],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 278145902,
                "osm_key": "amenity",
                "osm_value": "school",
                "type": "house",
                "postcode": "49506",
                "housenumber": "2425",
                "countrycode": "US",
                "name": "East Grand Rapids Middle School",
                "country": "United States",
                "city": "Grand Rapids",
                "street": "Lake Drive Southeast",
                "state": "MI",
                "county": "Kent",
                "extent": [-85.6102514, 42.9480353, -85.6066047, 42.945526],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.6083025923951, 42.94672525],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 1343904067,
                "osm_key": "amenity",
                "osm_value": "school",
                "type": "house",
                "postcode": "49506",
                "countrycode": "US",
                "name": "Grand Rapids Christian Middle School",
                "country": "United States",
                "city": "Grand Rapids",
                "district": "Third Ward",
                "street": "Chesaning Drive Southeast",
                "state": "Michigan",
                "county": "Kent",
                "extent": [-85.6177844, 42.9270635, -85.6139729, 42.9254628],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.61584126466617, 42.92606575],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 18117026,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "55744",
                "countrycode": "US",
                "name": "Millie Drive",
                "country": "United States",
                "city": "Grand Rapids",
                "state": "Minnesota",
                "county": "Itasca",
                "extent": [-93.5767978, 47.2135358, -93.5725599, 47.2134702],
            },
            "geometry": {"type": "Point", "coordinates": [-93.57467885, 47.213503]},
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 17874433,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49506",
                "countrycode": "US",
                "name": "Middleboro Drive Northeast",
                "country": "United States",
                "city": "Grand Rapids",
                "state": "Michigan",
                "county": "Kent",
                "extent": [-85.601564, 42.9653841, -85.5985334, 42.963531],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.6001882445008, 42.964658085962604],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 239528475,
                "osm_key": "building",
                "osm_value": "school",
                "type": "house",
                "postcode": "55744",
                "housenumber": "800",
                "countrycode": "US",
                "name": "Grand Rapids High School",
                "country": "United States",
                "city": "Grand Rapids",
                "street": "Northwest Conifer Drive",
                "state": "MN",
                "county": "Itasca",
                "extent": [-93.5434771, 47.2478622, -93.5408705, 47.2462115],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-93.54245174675202, 47.2470434],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 275435538,
                "osm_key": "amenity",
                "osm_value": "library",
                "type": "house",
                "postcode": "49506",
                "countrycode": "US",
                "name": "KDL - East Grand Rapids",
                "country": "United States",
                "city": "East Grand Rapids",
                "street": "Lakeside Drive Northeast",
                "state": "Michigan",
                "county": "Kent",
                "extent": [-85.6114351, 42.9488312, -85.6107144, 42.9482905],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.61097684137934, 42.948561749999996],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 225042679,
                "osm_key": "tourism",
                "osm_value": "hotel",
                "type": "house",
                "postcode": "49544",
                "housenumber": "500",
                "countrycode": "US",
                "name": "Hampton Inn Grand Rapids-North",
                "country": "United States",
                "city": "Grand Rapids",
                "street": "Center Drive Northwest",
                "state": "MI",
                "county": "Kent",
                "extent": [-85.6805531, 43.0184667, -85.6800055, 43.0179116],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.6802752460028, 43.0181957],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 1306265504,
                "osm_key": "shop",
                "osm_value": "cannabis",
                "type": "house",
                "postcode": "49505",
                "housenumber": "2701",
                "countrycode": "US",
                "name": "Grand Rapids Cannabis Company",
                "country": "United States",
                "city": "Grand Rapids",
                "street": "Oak Industrial Drive Northeast",
                "state": "MI",
                "county": "Kent",
                "extent": [-85.6038538, 42.9751122, -85.6036159, 42.9748549],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.60373987013213, 42.9749797],
            },
        },
        {
            "type": "Feature",
            "properties": {
                "osm_type": "W",
                "osm_id": 626579249,
                "osm_key": "highway",
                "osm_value": "residential",
                "type": "street",
                "postcode": "49525",
                "countrycode": "US",
                "name": "Kent Skills Center Drive",
                "country": "United States",
                "city": "Grand Rapids",
                "district": "Grand Rapids Charter Township",
                "state": "Michigan",
                "county": "Kent",
                "extent": [-85.5980312, 42.9946849, -85.597062, 42.9925804],
            },
            "geometry": {
                "type": "Point",
                "coordinates": [-85.59794255535043, 42.99378090604882],
            },
        },
    ],
    "query": "258 Piedmont Drive, Grand Rapids MI",
}
